# Generated by Django 5.2.3 on 2025-09-10 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alinti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField(verbose_name='Alıntı Metni')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yazar')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='Kaynak')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori')),
                ('isActive', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Alıntı',
                'verbose_name_plural': 'Alıntılar',
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('tur', models.CharField(choices=[('AKAID', 'Akaid (İtikad)'), ('FIKIH', 'Fıkıh (İbadet)'), ('SIYER', 'Siyer'), ('TECV', 'Tecvid')], max_length=5, unique=True)),
                ('aciklama', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='EzberSuresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sira', models.PositiveSmallIntegerField(choices=[(1, '1. Mülk Suresi'), (2, '2. Cin Suresi'), (3, '3. Kıyame Suresi'), (4, '4. Cuma Suresi'), (5, '5. Saff Suresi'), (6, '6. Rahman Suresi'), (7, '7. Vakia Suresi'), (8, '8. Fetih Suresi'), (9, '9. Hucurat Suresi'), (10, '10. Yasin Suresi'), (11, '11. Enfal Suresi'), (12, '12. İsra Suresi'), (13, '13. 30. Cüz Tamamı')], unique=True)),
                ('tahmini_sure', models.PositiveSmallIntegerField(default=7, help_text='Tahmini ezber süresi (gün)')),
                ('aciklama', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ezber Süresi',
                'verbose_name_plural': 'Ezber Süreleri',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('kayit_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('seviye', models.CharField(choices=[('HAZ1', 'Hazırlık 1. Seviye'), ('HAZ2', 'Hazırlık 2. Seviye'), ('HAZ3', 'Hazırlık 3. Seviye'), ('TEMEL', 'Temel Hafızlık'), ('ILERI', 'İleri Hafızlık')], default='HAZ1', max_length=5)),
                ('profil_foto', models.ImageField(blank=True, null=True, upload_to='ogrenci_profil/')),
                ('ozel_notlar', models.TextField(blank=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='SinavSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinav_tipi', models.CharField(choices=[('VIZE', 'Vize Sınavı'), ('FINAL', 'Final Sınavı'), ('QUIZ', 'Quiz'), ('PROJE', 'Proje'), ('SOZLU', 'Sözlü Sınavı')], max_length=10)),
                ('puan', models.PositiveSmallIntegerField()),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('aciklama', models.TextField(blank=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ogrenci')),
            ],
            options={
                'verbose_name': 'Sınav Sonucu',
                'verbose_name_plural': 'Sınav Sonuçları',
            },
        ),
        migrations.CreateModel(
            name='EzberKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('BASLAMADI', 'Başlamadı'), ('DEVAM', 'Devam Ediyor'), ('TAMAMLANDI', 'Tamamlandı')], default='BASLAMADI', max_length=10)),
                ('baslama_tarihi', models.DateField(blank=True, null=True)),
                ('bitis_tarihi', models.DateField(blank=True, null=True)),
                ('tahmini_bitis', models.DateField(blank=True, null=True)),
                ('gunluk_calisma', models.PositiveSmallIntegerField(default=1, help_text='Günlük çalışma saati')),
                ('zorluk', models.PositiveSmallIntegerField(choices=[(1, 'Kolay'), (2, 'Orta'), (3, 'Zor')], default=2)),
                ('yorum', models.TextField(blank=True)),
                ('ilerleme', models.IntegerField(default=0, verbose_name='İlerleme Yüzdesi')),
                ('sure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ezbersuresi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ogrenci')),
            ],
            options={
                'verbose_name': 'Ezber Kaydı',
                'verbose_name_plural': 'Ezber Kayıtları',
                'unique_together': {('ogrenci', 'sure')},
            },
        ),
        migrations.CreateModel(
            name='DersNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_degeri', models.PositiveSmallIntegerField(default=0)),
                ('yorum', models.TextField(blank=True)),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.ogrenci')),
            ],
            options={
                'verbose_name': 'Ders Notu',
                'verbose_name_plural': 'Ders Notları',
                'unique_together': {('ogrenci', 'ders', 'tarih')},
            },
        ),
    ]
